### ISSUE TITLE
Server hangs on start

### ISSUE THREAD

**Issue by paul13243546** [FredrikNoren/ungit#537]
For any repo, even an empty one, the server quickly hangs and then the webapp says "Connection lost".

last console line is always " - info: GET /api/baserepopath?path=whatever"

node.exe uses a lot of processing power and ~100MB of memory while hanging

I'm on Windows 7, fresh install of node. I can provide more logs and info if instructed how to

**Comment by paul13243546** [comment]
tried building source. get these errors on build

![image](https://cloud.githubusercontent.com/assets/1268656/7172345/2c663e9c-e3b4-11e4-8641-10086aae58b1.png)

**Comment by codingtwinky** [comment]
Latest ungit, 0.9.0, unfortunately have several problems with Windows.  This might be one of the side effects of  #528 as it is spawning too many windows and hog all memories.

**Comment by FredrikNoren** [comment]
@paul13243546 I've fixed that build error now: https://github.com/FredrikNoren/ungit/pull/539

**Comment by paul13243546** [comment]
I updated and tried again, same issue. (haven't tried building source yet)

**Comment by FredrikNoren** [comment]
@paul13243546 Yeah I haven't released it as a new version yet, since there are still more outstanding bugs that needs to be fixed. It is in the master branch though if you want to try to build from source

**Comment by codingtwinky** [comment]
@FredrikNoren Could you clarify on what are the outstanding issues?

**Comment by paul13243546** [comment]
Okay it builds fine, and the view looking at the ungit repo looks okay, but it still hangs when I try to point at a different repo.

**Comment by FredrikNoren** [comment]
@CodingTwinky: it doesn't seem to load pages properly, not sure what the
problem is. Maybe for some reason one of the git processes doesn't exit and
blocks others from starting or something, not sure just needs more
investigation

**Comment by paul13243546** [comment]
Just pulled and built latest version, still having the issue.

**Comment by FredrikNoren** [comment]
@paul13243546 can you try installing 0.9.2 and see if that version works?

**Comment by paul13243546** [comment]
Yeah that's the one I just tried. Are there some procedures to cleanup a previous install that could possibly fix the issue?

**Comment by FredrikNoren** [comment]
@paul13243546 Can you try the npm version (assuming your trying to build it from source now)? `npm uninstall -g ungit` and then `npm install -g ungit@latest` and finally `ungit` to start.

**Comment by paul13243546** [comment]
I did. Same issue.

**Comment by FredrikNoren** [comment]
Is anyone else seeing this issue?
